src/routes/college_controller.py
from flask import Blueprint, jsonify, render_template, request
from werkzeug import Response
from src.forms import CollegeForm
from src.entities import College
from src.model import SSIS
from src.routes import iterator_is_empty

colleges_bp = Blueprint("colleges", __name__)

@colleges_bp.route('', methods=['GET'])
def load_colleges() -> str:
    """
    Load the colleges content with an optional search filter.
    """
    # Get the search query and field from the request arguments
    search_query = request.args.get("search", "", type=str).strip().upper()
    search_field = request.args.get("field", "code", type=str).strip().lower()

    # Fetch colleges based on the search query and selected field if provided
    if search_query and search_field in ["code", "name"]:
        filter_kwargs = {search_field: search_query}  # Create a dynamic filter using the selected field
        colleges, is_empty = iterator_is_empty(SSIS.get_colleges(**filter_kwargs))
    else:
        colleges, is_empty = iterator_is_empty(SSIS.get_colleges())  # Fetch all colleges if no search query

    # Create a form instance for use in the modal
    college_form = CollegeForm()
    return render_template(
        'colleges_content.html', 
        colleges=colleges, 
        college_form=college_form, 
        is_empty=is_empty, 
        search_query=search_query,
        search_field=search_field
    )


@colleges_bp.route('/add', methods=['POST'])
def add_college() -> Response:
    """
    Handle form submission for adding a college.
    """
    form = CollegeForm()
    if form.validate_on_submit():
        new_college = College(
            code=form.code.data.upper(),
            name=form.name.data.upper(),
        )
        
        SSIS.add_college(new_college)
        
        # Return JSON response for AJAX success handling
        return jsonify(success=True, message="College added successfully!")
    
    # Return error message if form validation fails
    return jsonify(success=False, message=f"College {str(form.code.data)!r} already exists!")


@colleges_bp.route('/edit', methods=['POST'])
def edit_college() -> Response:
    """
    Handle form submission for editing an existing college.
    """
    form = CollegeForm()
    
    college = SSIS.get_college(str(form.code.data))
    if college:
        # Update the college with form data
        college.name = form.name.data.upper()
        
        try:
            SSIS.edit_college(college)
            # Return JSON response for AJAX success handling
            return jsonify(success=True, message="College updated successfully!")
        
        except Exception as e:
            return jsonify(success=False, message=f"Error: {e}")
    
    return jsonify(success=False, message=f"Program {str(form.code.data)!r} does not exist!")


@colleges_bp.route('/delete', methods=['POST'])
def delete_college() -> Response:
    """
    Route to handle deletion of a college by code.
    """
    college_code = request.form.get('code')
    
    if college_code:
        try:
            SSIS.delete_college(college_code)
            return jsonify(success=True, message="College deleted successfully!")
        
        except Exception as e:
            return jsonify(success=False, message=f"Failed to delete college\nError: {e}")
    
    return jsonify(success=False, message="Invalid college code.")

src/routes/program_controller.py
from flask import Blueprint, jsonify, render_template, request
from werkzeug import Response
from src.forms import ProgramForm
from src.entities import Program
from src.model import SSIS
from src.routes import iterator_is_empty

programs_bp = Blueprint("programs", __name__)

@programs_bp.route('', methods=['GET'])
def load_programs():
    """
    Load the programs content with an optional search filter.
    """
    # Get the search query and field from the request arguments
    search_query = request.args.get("search", "", type=str).strip().upper()
    search_field = request.args.get("field", "code", type=str).strip().lower()

    # Fetch programs based on the search query and selected field if provided
    if search_query and search_field in ["code", "name", "college"]:
        filter_kwargs = {search_field: search_query}  # Create a dynamic filter using the selected field
        programs, is_empty = iterator_is_empty(SSIS.get_programs(**filter_kwargs))
    else:
        programs, is_empty = iterator_is_empty(SSIS.get_programs())

    # Fetch colleges to populate the ProgramForm's college dropdown choices
    college_choices = [(college.code, college.name) for college in SSIS.get_colleges()]

    # Create a ProgramForm instance with dynamic college choices
    program_form = ProgramForm(college_list=college_choices)

    return render_template(
        'programs_content.html', 
        programs=programs, 
        program_form=program_form, 
        is_empty=is_empty,
        search_query=search_query,
        search_field=search_field
    )


@programs_bp.route('/add', methods=['POST'])
def add_program():
    """
    Handle form submission for adding a program.
    """
    form = ProgramForm(college_list=[(college.code, college.name) for college in SSIS.get_colleges()])
    
    if form.validate_on_submit():
        new_program = Program(
            code=form.code.data.upper(),
            name=form.name.data.upper(),
            college=form.college.data,
        )
        
        SSIS.add_program(new_program)

        # Return JSON response for AJAX success handling
        return jsonify(success=True, message="Program added successfully!")
    
    # Return error message if form validation fails
    return jsonify(success=False, message=f"Program {str(form.code.data)!r} already exists!")


@programs_bp.route('/edit', methods=['POST'])
def edit_program() -> Response:
    """
    Handle form submission for editing an existing program.
    """
    college_choices = [(college.code, college.name) for college in SSIS.get_colleges()]
    
    form = ProgramForm(college_list=college_choices, formdata=request.form)
    
    program = SSIS.get_program(str(form.code.data))
    if program:
        # Update the program with form data
        program.name = form.name.data.upper()
        program.college = form.college.data.upper()
        
        try:
            SSIS.edit_program(program)
            # Return JSON response for AJAX success handling
            return jsonify(success=True, message="Program updated successfully!")
        
        except Exception as e:
            return jsonify(success=False, message=f"Error: {e}")
    
    return jsonify(success=False, message=f"Program {str(form.code.data)!r} does not exist!")


@programs_bp.route('/delete', methods=['POST'])
def delete_program() -> Response:
    """
    Route to handle deletion of a program by code.
    """
    program_code = request.form.get('code')
    
    if program_code:
        try:
            SSIS.delete_program(program_code)
            return jsonify(success=True, message="Program deleted successfully!")
        
        except Exception as e:
            return jsonify(success=False, message=f"Failed to delete program\nError: {e}")
    
    return jsonify(success=False, message="Invalid program code.")

src/routes/student_controller.py
from flask import Blueprint, jsonify, render_template, request
from werkzeug import Response
from src.forms import StudentForm
from src.entities import Student
from src.model import SSIS
from src.routes import iterator_is_empty

students_bp = Blueprint("students", __name__)

@students_bp.route('', methods=['GET'])
def load_students():
    """
    Load the students content with an optional search filter.
    """
    # Get the search query and field from the request arguments
    search_query = request.args.get("search", "", type=str).strip().upper()
    search_field = request.args.get("field", "id", type=str).strip().lower()

    # Fetch students based on the search query and selected field if provided
    if search_query and search_field in ["id", "name", "year", "gender", "program"]:
        match search_field:
            case "id" | "year" | "program":
                filter_kwargs = {search_field: search_query}
            case "name":
                filter_kwargs = {"firstname": search_query, "lastname": search_query}
            case "gender":
                filter_kwargs = {"gender": {"MALE": "M", "FEMALE": "F", "OTHER": "O"}.get(search_query, "_")}
        
        students, is_empty = iterator_is_empty(SSIS.get_students(**filter_kwargs))
    
    else:
        students, is_empty = iterator_is_empty(SSIS.get_students())

    # Fetch programs to populate the StudentForm's program dropdown choices
    program_choices = [(program.code, program.name) for program in SSIS.get_programs()]

    # Create a StudentForm instance with dynamic program choices
    student_form = StudentForm(program_list=program_choices)

    return render_template(
        'students_content.html',
        students=students, 
        student_form=student_form, 
        is_empty=is_empty,
        search_query=search_query,
        search_field=search_field
    )


@students_bp.route('/add', methods=['POST'])
def add_student():
    """
    Handle form submission for adding a student.
    """
    # Get the program choices again to pass to the form for validation
    program_choices = [(program.code, program.name) for program in SSIS.get_programs()]
    
    form = StudentForm(program_list=program_choices, formdata=request.form)

    if form.validate_on_submit():
        # Create a new Student instance with the form data
        new_student = Student(
            id=form.id.data,
            firstname=form.firstname.data.upper(),
            lastname=form.lastname.data.upper(),
            year=form.year.data,
            gender=form.gender.data,
            program=form.program.data
        )
        
        SSIS.add_student(new_student)
        
        # Return JSON response for AJAX success handling
        return jsonify(success=True, message="Student added successfully!")
    
    # If validation fails, gather the error messages
    error_messages = []
    for field, errors in form.errors.items():
        for error in errors:
            error_messages.append(f"{field}: {error}")

    # Return a JSON response with validation errors
    return jsonify(success=False, message="Validation errors: " + ", ".join(error_messages))


@students_bp.route('/edit', methods=['POST'])
def edit_student():
    """
    Handle form submission for editing an existing student.
    """
    # Get the program choices again to pass to the form for validation
    program_choices = [(program.code, program.name) for program in SSIS.get_programs()]
    
    form = StudentForm(program_list=program_choices, formdata=request.form)

    student = SSIS.get_student(str(form.id.data))
    if student:
        # Update the student with the new form data
        student.firstname = form.firstname.data.upper()
        student.lastname = form.lastname.data.upper()
        student.year = form.year.data
        student.gender = form.gender.data
        student.program = form.program.data
        
        try:
            # Update the student in the database
            SSIS.edit_student(student)
            
            # Return JSON response for AJAX success handling
            return jsonify(success=True, message="Student updated successfully!")
        
        except Exception as e:
            return jsonify(success=False, message=f"Error: {e}")

    return jsonify(success=False, message=f"Student {str(form.id.data)} does not exist!")


@students_bp.route('/delete', methods=['POST'])
def delete_student() -> Response:
    """
    Route to handle deletion of a student by id.
    """
    student_id = request.form.get('id')
    
    if student_id:
        try:
            SSIS.delete_student(student_id)
            return jsonify(success=True, message="Student deleted successfully!")
        
        except Exception as e:
            return jsonify(success=False, message=f"Failed to delete student\nError: {e}")
    
    return jsonify(success=False, message="Invalid student id.")

src/templates/colleges_content.html
<div class="mt-4" id="collegesTable">
    <!-- Container with flexbox utilities for alignment -->
    <div class="d-flex justify-content-between align-items-center mb-3">
        <!-- Search Bar for Filtering Colleges -->
        <form id="searchForm" method="GET" action="{{ url_for('colleges.load_colleges') }}" class="form-inline" data-entity="colleges">
            <!-- Dropdown for selecting the field to search by -->
            <select name="field" class="form-control mr-2">
                <option value="code" {% if search_field == "code" %}selected{% endif %}>Code</option>
                <option value="name" {% if search_field == "name" %}selected{% endif %}>Name</option>
            </select>
            <input type="text" name="search" class="form-control mr-2" autocapitalize="characters" placeholder="Search by Code or Name" value="{{ search_query }}">
            <button type="submit" class="btn btn-primary">Search</button>
        </form>

        <!-- Button to open the "Add College" form modal -->
        <button class="btn btn-success" onclick="showCollegeForm('add')">Add New College</button>
    </div>

    <!-- Colleges Table -->
    <div class="table-responsive">
        <table class="table table-borderless table-striped text-center table-hover sticky">
            <thead class="thead-dark">
                <tr>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for college in colleges %}
                <tr>
                    <td>{{ college.code }}</td>
                    <td>{{ college.name }}</td>
                    <td>
                        <button class="btn btn-sm btn-warning" onclick="showCollegeForm('edit', '{{ college.code }}', '{{ college.name }}')">Edit</button>
                        <form class="delete-form" action="{{ url_for('colleges.delete_college') }}" method="POST" style="display:inline;" data-entity="colleges">
                            {{ college_form.hidden_tag() }}
                            <input type="hidden" name="code" value="{{ college.code }}">
                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this college? This will also delete every program and unenroll every student under it.')">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- No Colleges Found Message -->
    {% if is_empty %}
        <div class="alert alert-warning text-center" role="alert">
            No colleges found.
        </div>
    {% endif %}
</div>

<!-- Modal for Adding/Editing Colleges -->
<div class="modal fade" id="collegeFormModal" tabindex="-1" role="dialog" aria-labelledby="collegeFormModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-bottom" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="collegeFormModalLabel">Add/Edit College</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- College Flask-WTF Form -->
                <form method="POST" id="collegeForm" class="modal-form" data-entity="colleges">
                    {{ college_form.hidden_tag() }}
                    <div class="form-group">
                        {{ college_form.code.label(class="form-control-label") }}
                        {{ college_form.code(class="form-control", autocapitalize="characters") }}
                    </div>
                    <div class="form-group">
                        {{ college_form.name.label(class="form-control-label") }}
                        {{ college_form.name(class="form-control", autocapitalize="characters") }}
                    </div>
                    <button type="submit" action="{{ url_for('colleges.load_colleges') }}" class="btn btn-primary" id="saveCollegeButton">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- JavaScript for Modal Form Handling -->
<script>
    function showCollegeForm(action, code='', name='') {
        $('#collegeFormModal').modal('show');

        const form = document.getElementById('collegeForm');

        if (action === 'add') {
            form.action = "{{ url_for('colleges.add_college') }}";
            document.getElementById('collegeFormModalLabel').innerText = 'Add College';

            // Clear form fields for adding
            form.code.value = '';
            form.name.value = '';
            
            const codeField = document.getElementById('collegeForm').code;
            codeField.readOnly = false;

        } else if (action === 'edit') {
            form.action = `{{ url_for('colleges.edit_college') }}`;
            document.getElementById('collegeFormModalLabel').innerText = 'Edit College';

            // Populate form fields with existing data
            form.code.value = code;
            form.name.value = name;
            
            const codeField = document.getElementById('collegeForm').code;
            codeField.readOnly = true;
        }
    }
</script>

src/templates/programs_content.html
<div class="mt-4" id="programsTable">
    <!-- Container with flexbox utilities for alignment -->
    <div class="d-flex justify-content-between align-items-center mb-3">
        <!-- Search Bar for Filtering Programs -->
        <form id="searchForm" method="GET" action="{{ url_for('programs.load_programs') }}" class="form-inline" data-entity="programs">
            <!-- Dropdown for selecting the field to search by -->
            <select name="field" class="form-control mr-2">
                <option value="code" {% if search_field == "code" %}selected{% endif %}>Code</option>
                <option value="name" {% if search_field == "name" %}selected{% endif %}>Name</option>
                <option value="college" {% if search_field == "college" %}selected{% endif %}>College Code</option>
            </select>
            <input type="text" name="search" class="form-control mr-2" autocapitalize="characters"  placeholder="Search", value="{{ search_query }}">
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
        
        <!-- Button to open the "Add Program" form modal -->
        <button class="btn btn-success" onclick="showProgramForm('add')">Add New Program</button>
    </div>

    <!-- Programs Table -->
    <div class="table-responsive">
        <table class="table table-borderless table-striped text-center table-hover sticky">
            <thead class="thead-dark">
                <tr>
                    <th>Code</th>
                    <th>Name</th>
                    <th>College</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for program in programs %}
                <tr>
                    <td>{{ program.code }}</td>
                    <td>{{ program.name }}</td>
                    <td>{{ program.college }}</td>
                    <td>
                        <button class="btn btn-sm btn-warning" onclick="showProgramForm('edit', '{{ program.code }}', '{{ program.name }}', '{{ program.college }}')">Edit</button>
                        <form class="delete-form" action="{{ url_for('programs.delete_program') }}" method="POST" style="display:inline;" data-entity="programs">
                            {{ program_form.hidden_tag() }}
                            <input type="hidden" name="code" value="{{ program.code }}">
                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this program? This action will unenroll all students under this program.')">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- Modal for Adding/Editing Programs -->
<div class="modal fade" id="programFormModal" tabindex="-1" role="dialog" aria-labelledby="programFormModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-bottom" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="programFormModalLabel">Add/Edit Program</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Program Flask-WTF Form -->
                <form method="POST" id="programForm" class="modal-form" data-entity="programs">
                    {{ program_form.hidden_tag() }}
                    <div class="form-group">
                        {{ program_form.code.label(class="form-control-label") }}
                        {{ program_form.code(class="form-control", autocapitalize="characters" ) }}
                    </div>
                    <div class="form-group">
                        {{ program_form.name.label(class="form-control-label") }}
                        {{ program_form.name(class="form-control", autocapitalize="characters" ) }}
                    </div>
                    <div class="form-group">
                        {{ program_form.college.label(class="form-control-label") }}
                        {{ program_form.college(class="form-control") }}
                    </div>
                    <button type="submit" action="{{ url_for('programs.load_programs') }}" class="btn btn-primary" id="saveProgramButton">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- JavaScript for Modal Form Handling -->
<script>
    function showProgramForm(action, code='', name='', college='') {
        $('#programFormModal').modal('show');

        const form = document.getElementById('programForm');

        if (action === 'add') {
            form.action = "{{ url_for('programs.add_program') }}";
            document.getElementById('programFormModalLabel').innerText = 'Add Program';

            // Clear form fields for adding
            form.code.value = '';
            form.name.value = '';
            form.college.value = '';
            
            const codeField = document.getElementById('programForm').code;
            codeField.readOnly = false;

        } else if (action === 'edit') {
            form.action = `{{ url_for('programs.edit_program') }}`;
            document.getElementById('programFormModalLabel').innerText = 'Edit Program';

            // Populate form fields with existing data
            form.code.value = code;
            form.name.value = name;
            form.college.value = college;

            const codeField = document.getElementById('programForm').code;
            codeField.readOnly = true;
        }
    }
</script>

src/templates/students_content.html
<div class="mt-4">
    <!-- Container with flexbox utilities for alignment -->
    <div class="d-flex justify-content-between align-items-center mb-3">
        <!-- Search Bar for Filtering Students -->
        <form id="searchForm" method="GET" action="{{ url_for('students.load_students') }}" class="form-inline" data-entity="students">
            <!-- Dropdown for selecting the field to search by -->
            <select name="field" class="form-control mr-2">
                <option value="id" {% if search_field == "id" %}selected{% endif %}>ID</option>
                <option value="name" {% if search_field == "name" %}selected{% endif %}>Name</option>
                <option value="year" {% if search_field == "year" %}selected{% endif %}>Year</option>
                <option value="gender" {% if search_field == "gender" %}selected{% endif %}>Gender</option>
                <option value="program" {% if search_field == "program" %}selected{% endif %}>Program Code</option>
            </select>
            <input type="text" name="search" class="form-control mr-2" autocapitalize="characters"  placeholder="Search Students" value="{{ search_query }}">
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
        
        <!-- Button to open the "Add Student" form modal -->
        <button class="btn btn-success" onclick="showStudentForm('add')">Add New Student</button>
    </div>

    <!-- Students Table -->
    <div class="table-responsive">
        <table class="table table-borderless table-striped text-center table-hover sticky">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Year</th>
                    <th>Gender</th>
                    <th>Program</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{ student.id }}</td>
                    <td>{{ student.fullname }}</td>
                    <td>{{ student.year }}</td>
                    <td>{{ student.gender }}</td>
                    <td>{{ student.program }}</td>
                    <td>
                        <button class="btn btn-sm btn-warning" onclick="showStudentForm('edit', 
                            '{{ student.id }}', 
                            '{{ student.firstname }}', 
                            '{{ student.lastname }}', 
                            '{{ student.year }}', 
                            '{{ student.gender.value }}', 
                            '{{ student.program }}')
                        ">Edit</button>
                        <form class="delete-form" action="{{ url_for('students.delete_student') }}" method="POST" style="display:inline;" data-entity="students">
                            {{ student_form.hidden_tag() }}
                            <input type="hidden" name="id" value="{{ student.id }}">
                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this student?')">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- No Colleges Found Message -->
    {% if is_empty %}
        <div class="alert alert-warning text-center" role="alert">
            No students found.
        </div>
    {% endif %}
</div>

<!-- Modal for Adding/Editing Students -->
<div class="modal fade" id="studentFormModal" tabindex="-1" role="dialog" aria-labelledby="studentFormModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-bottom" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="studentFormModalLabel">Add/Edit Student</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Student Flask-WTF Form -->
                <form method="POST" id="studentForm" class="modal-form" data-entity="students">
                    {{ student_form.hidden_tag() }}
                    <div class="form-group">
                        {{ student_form.id.label(class="form-control-label") }}
                        {{ student_form.id(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ student_form.firstname.label(class="form-control-label") }}
                        {{ student_form.firstname(class="form-control", autocapitalize="characters" ) }}
                    </div>
                    <div class="form-group">
                        {{ student_form.lastname.label(class="form-control-label") }}
                        {{ student_form.lastname(class="form-control", autocapitalize="characters" ) }}
                    </div>
                    <div class="form-group d-flex justify-content-between">
                        <div>
                            {{ student_form.year.label(class="form-control-label") }}
                            {{ student_form.year(class="form-control") }}
                        </div>
                        <div>
                            {{ student_form.gender.label(class="form-control-label") }}
                            <div class="form-check">
                                {% for subfield in student_form.gender %}
                                    <div class="form-check form-check-inline">
                                        {{ subfield(class="form-check-input") }}
                                        {{ subfield.label(class="form-check-label") }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        {{ student_form.program.label(class="form-control-label") }}
                        {{ student_form.program(class="form-control") }}
                    </div>
                    <button type="submit" class="btn btn-primary" id="saveStudentButton">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- JavaScript for Handling the Modal -->
<script>
    // Show the modal and set up the form for add or edit action
    function showStudentForm(action, id='', firstname='', lastname='', year='', gender='', program='') {
        $('#studentFormModal').modal('show');

        const form = document.getElementById('studentForm');

        if (action === 'add') {
            form.action = "{{ url_for('students.add_student') }}";
            document.getElementById('studentFormModalLabel').innerText = 'Add Student';

            // Clear form fields for adding
            form.id.value = '';
            form.firstname.value = '';
            form.lastname.value = '';
            form.year.value = '';
            form.gender.value = '';
            form.program.value = '';

            const idField = document.getElementById('studentForm').id;
            idField.readOnly = false;

        } else if (action === 'edit') {
            form.action = "{{ url_for('students.edit_student') }}";
            document.getElementById('studentFormModalLabel').innerText = 'Edit Student';

            // Populate form fields with existing data
            form.id.value = id;
            form.firstname.value = firstname;
            form.lastname.value = lastname;
            form.year.value = year;
            form.gender.value = gender[0];
            form.program.value = program;
            
            const idField = document.getElementById('studentForm').id;
            idField.readOnly = true;
        }
    }
</script>